
---1
WITH managers AS
(SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.HIRE_DATE FROM
(SELECT UNIQUE EMPLOYEES.MANAGER_ID FROM EMPLOYEES WHERE EMPLOYEES.MANAGER_ID IS NOT NULL) managers_id
INNER JOIN EMPLOYEES
ON managers_id.MANAGER_ID = EMPLOYEES.EMPLOYEE_ID)

SELECT * FROM managers
WHERE managers.HIRE_DATE = (SELECT MAX(managers.HIRE_DATE) FROM managers)
ORDER BY managers.EMPLOYEE_ID

---2
WITH emloyees_avg_dep_sal AS
(SELECT EMPLOYEES.DEPARTMENT_ID, EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.LAST_NAME, EMPLOYEES.SALARY, AVG(EMPLOYEES.SALARY) OVER (PARTITION BY EMPLOYEES.DEPARTMENT_ID) AS average_salary 
FROM EMPLOYEES
WHERE EMPLOYEES.DEPARTMENT_ID IS NOT NULL)

SELECT DEPARTMENT_ID, EMPLOYEE_ID, LAST_NAME, SALARY FROM emloyees_avg_dep_sal WHERE emloyees_avg_dep_sal.SALARY > average_salary
ORDER BY DEPARTMENT_ID, SALARY, LAST_NAME

---3
WITH emloyees_min_dep_sal AS
(SELECT EMPLOYEES.DEPARTMENT_ID, EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.LAST_NAME, EMPLOYEES.SALARY, MIN(EMPLOYEES.SALARY) OVER (PARTITION BY EMPLOYEES.DEPARTMENT_ID) AS min_salary 
FROM EMPLOYEES
WHERE EMPLOYEES.DEPARTMENT_ID IS NOT NULL)

SELECT DEPARTMENT_ID, EMPLOYEE_ID, LAST_NAME, SALARY FROM emloyees_min_dep_sal WHERE emloyees_min_dep_sal.SALARY = min_salary 
ORDER BY DEPARTMENT_ID, SALARY, LAST_NAME


---4

WITH europe_managers_sc AS
(
SELECT europe_managers.EMPLOYEE_ID, europe_managers.SALARY, COUNT(EMPLOYEES.EMPLOYEE_ID) AS subord_count FROM
(
SELECT managers.EMPLOYEE_ID, managers.SALARY FROM
(SELECT DEPARTMENTS.DEPARTMENT_ID FROM
DEPARTMENTS
INNER JOIN (SELECT LOCATIONS.LOCATION_ID FROM LOCATIONS WHERE LOCATIONS.COUNTRY_ID IN (SELECT COUNTRIES.COUNTRY_ID FROM COUNTRIES
WHERE COUNTRIES.REGION_ID IN (SELECT REGIONS.REGION_ID FROM REGIONS WHERE REGIONS.REGION_NAME = 'Europe'))) eu_loc
ON DEPARTMENTS.LOCATION_ID = eu_loc.LOCATION_ID) eu_departments

INNER JOIN
(SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.SALARY, EMPLOYEES.DEPARTMENT_ID FROM
(SELECT UNIQUE EMPLOYEES.MANAGER_ID FROM EMPLOYEES WHERE EMPLOYEES.MANAGER_ID IS NOT NULL) managers_id
INNER JOIN EMPLOYEES
ON managers_id.MANAGER_ID = EMPLOYEES.EMPLOYEE_ID) managers

ON managers.DEPARTMENT_ID = eu_departments.DEPARTMENT_ID) europe_managers
INNER JOIN EMPLOYEES
ON EMPLOYEES.MANAGER_ID = europe_managers.EMPLOYEE_ID

GROUP BY europe_managers.EMPLOYEE_ID, europe_managers.SALARY
ORDER BY subord_count DESC
)

SELECT * FROM
(SELECT EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, EMPLOYEES.SALARY FROM EMPLOYEES
WHERE EMPLOYEES.DEPARTMENT_ID IN 
(SELECT DEPARTMENTS.DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENTS.LOCATION_ID IN 
(SELECT LOCATIONS.LOCATION_ID FROM LOCATIONS WHERE LOCATIONS.COUNTRY_ID IN 
(SELECT COUNTRIES.COUNTRY_ID FROM COUNTRIES WHERE COUNTRIES.REGION_ID IN 
(SELECT REGIONS.REGION_ID FROM REGIONS WHERE REGIONS.REGION_NAME = 'Americas')))))
america_employees

WHERE

america_employees.SALARY >

(SELECT AVG(europe_managers_max_sc.SALARY) AS avg_sal FROM
(SELECT europe_managers_sc.EMPLOYEE_ID, europe_managers_sc.SALARY, europe_managers_sc.subord_count
FROM europe_managers_sc 
WHERE europe_managers_sc.subord_count = (SELECT MAX(subord_count) FROM europe_managers_sc)) europe_managers_max_sc)

ORDER BY LAST_NAME, FIRST_NAME DESC

---5
SELECT prev_result.DEPARTMENT_ID, prev_result.DEPARTMENT_NAME, NVL(prev_result.sum_empl_sal, 0) AS sum_empl_sal, NVL(ROUND((prev_result.sum_empl_sal / prev_result.sum_sal) * 100, 2), 0) AS percent_from_sum_sal FROM
(SELECT * FROM
(SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, ROUND(SUM(EMPLOYEES.SALARY), 2) AS sum_empl_sal FROM
DEPARTMENTS LEFT JOIN EMPLOYEES
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME) dep_sum_sal
CROSS JOIN
(SELECT SUM(EMPLOYEES.SALARY) AS sum_sal FROM EMPLOYEES) t) prev_result

UNION

SELECT null_dep_empl.DEPARTMENT_ID, NVL(dep.DEPARTMENT_NAME, 'no department'), null_dep_empl.sum_empl_sal, ROUND((null_dep_empl.sum_empl_sal / t.sum_sal) * 100, 2) AS percent_from_sum_sal FROM
(SELECT SUM(EMPLOYEES.SALARY) AS SUM_empl_sal, EMPLOYEES.DEPARTMENT_ID FROM EMPLOYEES
GROUP BY EMPLOYEES.DEPARTMENT_ID
HAVING EMPLOYEES.DEPARTMENT_ID IS NULL) null_dep_empl
LEFT OUTER JOIN
(SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME FROM DEPARTMENTS) dep
ON dep.DEPARTMENT_ID = null_dep_empl.DEPARTMENT_ID
CROSS JOIN
(SELECT SUM(EMPLOYEES.SALARY) AS sum_sal FROM EMPLOYEES) t

ORDER BY DEPARTMENT_ID, sum_empl_sal, percent_from_sum_sal DESC

---6

SELECT prev_result.DEPARTMENT_ID, prev_result.DEPARTMENT_NAME, NVL(prev_result.avg_empl_sal, 0) AS avg_empl_sal, NVL(ROUND((prev_result.avg_empl_sal / prev_result.avg_sal) * 100, 2), 0) AS percent_from_avg_sal FROM
(SELECT * FROM
(SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, ROUND(AVG(EMPLOYEES.SALARY), 2) AS avg_empl_sal FROM
DEPARTMENTS LEFT JOIN EMPLOYEES
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME) dep_avg_sal
CROSS JOIN
(SELECT AVG(EMPLOYEES.SALARY) AS avg_sal FROM EMPLOYEES) t) prev_result

UNION

SELECT null_dep_empl.DEPARTMENT_ID, NVL(dep.DEPARTMENT_NAME, 'no department'), null_dep_empl.avg_empl_sal, ROUND((null_dep_empl.avg_empl_sal / t.avg_sal) * 100, 2) AS percent_from_avg_sal FROM
(SELECT AVG(EMPLOYEES.SALARY) AS avg_empl_sal, EMPLOYEES.DEPARTMENT_ID FROM EMPLOYEES
GROUP BY EMPLOYEES.DEPARTMENT_ID
HAVING EMPLOYEES.DEPARTMENT_ID IS NULL) null_dep_empl
LEFT OUTER JOIN
(SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME FROM DEPARTMENTS) dep
ON dep.DEPARTMENT_ID = null_dep_empl.DEPARTMENT_ID
CROSS JOIN
(SELECT AVG(EMPLOYEES.SALARY) AS avg_sal FROM EMPLOYEES) t

ORDER BY DEPARTMENT_ID, avg_empl_sal, percent_from_avg_sal DESC

---7

SELECT EMPLOYEES.FIRST_NAME, COUNT(*) AS count_with_this_name FROM EMPLOYEES
GROUP BY EMPLOYEES.FIRST_NAME
ORDER BY count_with_this_name DESC, FIRST_NAME

---8
WITH america_dep AS
(SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENTS.LOCATION_ID IN 
(SELECT LOCATIONS.LOCATION_ID FROM LOCATIONS WHERE LOCATIONS.COUNTRY_ID IN 
(SELECT COUNTRIES.COUNTRY_ID FROM COUNTRIES WHERE COUNTRIES.REGION_ID IN 
(SELECT REGIONS.REGION_ID FROM REGIONS WHERE REGIONS.REGION_NAME = 'Americas')))),
empl_first AS 
(SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.DEPARTMENT_ID FROM EMPLOYEES INNER JOIN america_dep ON america_dep.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID 
WHERE EMPLOYEES.MANAGER_ID IS NULL),
empl_second AS 
(SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.DEPARTMENT_ID FROM EMPLOYEES INNER JOIN america_dep ON america_dep.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID 
WHERE EMPLOYEES.MANAGER_ID IN (SELECT empl_first.EMPLOYEE_ID FROM empl_first)),
empl_third AS 
(SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.DEPARTMENT_ID FROM EMPLOYEES INNER JOIN america_dep ON america_dep.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID 
WHERE EMPLOYEES.MANAGER_ID IN (SELECT empl_second.EMPLOYEE_ID FROM empl_second)),
empl_first_count AS 
(SELECT COUNT(empl_first.EMPLOYEE_ID) AS first_level_count, empl_first.DEPARTMENT_ID FROM empl_first GROUP BY empl_first.DEPARTMENT_ID),
empl_second_count AS 
(SELECT COUNT(empl_second.EMPLOYEE_ID) AS second_level_count, empl_second.DEPARTMENT_ID FROM empl_second GROUP BY empl_second.DEPARTMENT_ID),
empl_third_count AS 
(SELECT COUNT(empl_third.EMPLOYEE_ID) AS third_level_count, empl_third.DEPARTMENT_ID FROM empl_third GROUP BY empl_third.DEPARTMENT_ID)


SELECT america_dep.DEPARTMENT_NAME, NVL(empl_first_count.first_level_count, 0) AS first_level_count, NVL(empl_second_count.second_level_count, 0) AS second_level_count, NVL(empl_third_count.third_level_count, 0) AS third_level_count FROM
america_dep
LEFT OUTER JOIN empl_first_count ON america_dep.DEPARTMENT_ID = empl_first_count.DEPARTMENT_ID
LEFT OUTER JOIN empl_second_count ON america_dep.DEPARTMENT_ID = empl_second_count.DEPARTMENT_ID
LEFT OUTER JOIN empl_third_count ON america_dep.DEPARTMENT_ID = empl_third_count.DEPARTMENT_ID
ORDER BY DEPARTMENT_NAME

---9
WITH americas_salary AS
(SELECT empl.DEPARTMENT_ID, dep.DEPARTMENT_NAME, empl.EMPLOYEE_ID, empl.SALARY FROM
(SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.DEPARTMENT_ID, EMPLOYEES.SALARY FROM EMPLOYEES) empl
INNER JOIN
(SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENTS.LOCATION_ID IN 
(SELECT LOCATIONS.LOCATION_ID FROM LOCATIONS WHERE LOCATIONS.COUNTRY_ID IN 
(SELECT COUNTRIES.COUNTRY_ID FROM COUNTRIES WHERE COUNTRIES.REGION_ID IN 
(SELECT REGIONS.REGION_ID FROM REGIONS WHERE REGIONS.REGION_NAME = 'Americas')))) dep
ON dep.DEPARTMENT_ID = empl.DEPARTMENT_ID) 

SELECT DEPARTMENT_NAME FROM
(SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, MIN(EMPLOYEES.SALARY) AS min_dep_sal FROM
DEPARTMENTS
INNER JOIN
EMPLOYEES
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME) t
WHERE t.min_dep_sal > (SELECT AVG(americas_salary.SALARY) FROM americas_salary)

---10

WITH dep_empl_count AS
(SELECT DEPARTMENTS.DEPARTMENT_ID, COUNT(EMPLOYEES.EMPLOYEE_ID) AS empl_count FROM
DEPARTMENTS INNER JOIN EMPLOYEES
ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
GROUP BY DEPARTMENTS.DEPARTMENT_ID)

SELECT SUM(EMPLOYEES.SALARY) AS sum_salary, min_dep.DEPARTMENT_ID FROM
(SELECT dep_empl_count.DEPARTMENT_ID FROM dep_empl_count WHERE empl_count = (SELECT MIN(empl_count) FROM dep_empl_count)) min_dep
INNER JOIN EMPLOYEES
ON EMPLOYEES.DEPARTMENT_ID = min_dep.DEPARTMENT_ID
GROUP BY min_dep.DEPARTMENT_ID
ORDER BY DEPARTMENT_ID DESC

---11

SELECT EMPLOYEES.LAST_NAME, COUNT(EMPLOYEES.LAST_NAME) AS surname_count FROM EMPLOYEES
GROUP BY EMPLOYEES.LAST_NAME
ORDER BY LAST_NAME

---12

WITH dep_count_country AS
(SELECT COUNT(dep.DEPARTMENT_ID) AS dep_count, COUNTRIES.COUNTRY_ID FROM
(SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.LOCATION_ID FROM DEPARTMENTS) dep
INNER JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = dep.LOCATION_ID
INNER JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
GROUP BY COUNTRIES.COUNTRY_ID),

max_dep_country AS (SELECT COUNTRY_ID FROM dep_count_country WHERE dep_count_country.dep_count = (SELECT MAX(dep_count_country.dep_count) FROM dep_count_country)),

result AS (SELECT EMPLOYEES.EMPLOYEE_ID, t.DEPARTMENT_ID, t.SALARY, COUNTRIES.COUNTRY_ID FROM
(SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.SALARY, EMPLOYEES.DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEES.DEPARTMENT_ID IN
(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENTS.LOCATION_ID IN
(SELECT LOCATIONS.LOCATION_ID FROM LOCATIONS WHERE LOCATIONS.COUNTRY_ID = (SELECT max_dep_country.COUNTRY_ID FROM max_dep_country)))) t
INNER JOIN EMPLOYEES
ON EMPLOYEES.EMPLOYEE_ID = t.EMPLOYEE_ID
INNER JOIN DEPARTMENTS
ON DEPARTMENTS.DEPARTMENT_ID = t.DEPARTMENT_ID
INNER JOIN LOCATIONS
ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
INNER JOIN COUNTRIES
ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID)

SELECT result.country_id, result.employee_id FROM
result where result.salary = (SELECT MAX(result.salary) from result)
order by country_id, employee_id

---13

WITH dep_count_country AS
(SELECT COUNT(dep.DEPARTMENT_ID) AS dep_count, COUNTRIES.COUNTRY_ID FROM
(SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.LOCATION_ID FROM DEPARTMENTS) dep
INNER JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = dep.LOCATION_ID
INNER JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
GROUP BY COUNTRIES.COUNTRY_ID),

max_dep_country AS (SELECT COUNTRY_ID FROM dep_count_country WHERE dep_count_country.dep_count = (SELECT MAX(dep_count_country.dep_count) FROM dep_count_country)),

result AS (SELECT EMPLOYEES.EMPLOYEE_ID, t.DEPARTMENT_ID, COUNTRIES.COUNTRY_ID FROM
(SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEES.DEPARTMENT_ID IN
(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENTS.LOCATION_ID IN
(SELECT LOCATIONS.LOCATION_ID FROM LOCATIONS WHERE LOCATIONS.COUNTRY_ID = (SELECT max_dep_country.COUNTRY_ID FROM max_dep_country)))) t
INNER JOIN EMPLOYEES
ON EMPLOYEES.EMPLOYEE_ID = t.EMPLOYEE_ID
INNER JOIN DEPARTMENTS
ON DEPARTMENTS.DEPARTMENT_ID = t.DEPARTMENT_ID
INNER JOIN LOCATIONS
ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
INNER JOIN COUNTRIES
ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID),

sub_count AS (SELECT COUNT(EMPLOYEES.EMPLOYEE_ID) AS subord_count, EMPLOYEES.MANAGER_ID
FROM EMPLOYEES
GROUP BY
EMPLOYEES.MANAGER_ID
HAVING EMPLOYEES.MANAGER_ID IS NOT NULL),

result_table AS
(SELECT result.EMPLOYEE_ID, result.COUNTRY_ID, sub_count.SUBORD_COUNT FROM result
INNER JOIN sub_count
ON result.EMPLOYEE_ID = sub_count.MANAGER_ID)

SELECT result_table.COUNTRY_ID, result_table.EMPLOYEE_ID FROM result_table
where result_table.SUBORD_COUNT = (SELECT MAX(SUBORD_COUNT) FROM result_table)
order by country_id, employee_id

---14

WITH country AS
(SELECT UNIQUE COUNTRY_ID FROM
(SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.DEPARTMENT_ID FROM EMPLOYEES
WHERE EMPLOYEES.HIRE_DATE = (SELECT MAX(EMPLOYEES.HIRE_DATE) FROM EMPLOYEES)) T
INNER JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = T.DEPARTMENT_ID
INNER JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
INNER JOIN COUNTRIES ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID),

sub_count AS (SELECT COUNT(EMPLOYEES.EMPLOYEE_ID) AS subord_count, EMPLOYEES.MANAGER_ID
FROM EMPLOYEES
GROUP BY
EMPLOYEES.MANAGER_ID
HAVING EMPLOYEES.MANAGER_ID IS NOT NULL),

result AS (SELECT T.employee_id, country_id, T.subord_count FROM
(SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.DEPARTMENT_ID, sub_count.subord_count FROM sub_count INNER JOIN EMPLOYEES ON EMPLOYEES.EMPLOYEE_ID = sub_count.MANAGER_ID) T 
INNER JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = T.DEPARTMENT_ID
INNER JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
WHERE LOCATIONS.COUNTRY_ID = (SELECT country.COUNTRY_ID FROM country))

SELECT result.EMPLOYEE_ID FROM result
where result.subord_count = (select max(result.subord_count) from result)

---15

WITH country AS
(SELECT UNIQUE COUNTRY_ID FROM
(SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.DEPARTMENT_ID FROM EMPLOYEES
WHERE EMPLOYEES.HIRE_DATE = (SELECT MIN(EMPLOYEES.HIRE_DATE) FROM EMPLOYEES)) T
INNER JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = T.DEPARTMENT_ID
INNER JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
INNER JOIN COUNTRIES ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID),

managers AS (SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.DEPARTMENT_ID, T.sum_emp_sal FROM 
(SELECT SUM(EMPLOYEES.SALARY) sum_emp_sal, EMPLOYEES.MANAGER_ID FROM
EMPLOYEES
GROUP BY EMPLOYEES.MANAGER_ID
HAVING MANAGER_ID IS NOT NULL) T
INNER JOIN EMPLOYEES ON EMPLOYEES.EMPLOYEE_ID = T.MANAGER_ID),

result AS

(SELECT managers.EMPLOYEE_ID, managers.sum_emp_sal FROM
managers INNER JOIN DEPARTMENTS
ON DEPARTMENTS.DEPARTMENT_ID = MANAGERS.DEPARTMENT_ID
INNER JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
WHERE LOCATIONS.COUNTRY_ID = (SELECT country.COUNTRY_ID FROM country))

SELECT result.EMPLOYEE_ID FROM result
WHERE result.sum_emp_sal = (SELECT MAX(result.sum_emp_sal) FROM result)

---16
with result as
(SELECT COUNT(emp_year.EMPLOYEE_ID) emp_count, emp_year.year FROM
(SELECT EXTRACT(YEAR FROM EMPLOYEES.HIRE_DATE) AS year, EMPLOYEES.EMPLOYEE_ID FROM EMPLOYEES) emp_year
GROUP BY emp_year.year)

SELECT year from result
where emp_count = (SELECT MAX(emp_count) FROM result)