
---1
WITH managers AS
(SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.HIRE_DATE FROM
(SELECT UNIQUE EMPLOYEES.MANAGER_ID FROM EMPLOYEES WHERE EMPLOYEES.MANAGER_ID IS NOT NULL) managers_id
INNER JOIN EMPLOYEES
ON managers_id.MANAGER_ID = EMPLOYEES.EMPLOYEE_ID)

SELECT * FROM managers
WHERE managers.HIRE_DATE = (SELECT MAX(managers.HIRE_DATE) FROM managers)
ORDER BY managers.EMPLOYEE_ID

---2
WITH emloyees_avg_dep_sal AS
(SELECT EMPLOYEES.DEPARTMENT_ID, EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.LAST_NAME, EMPLOYEES.SALARY, AVG(EMPLOYEES.SALARY) OVER (PARTITION BY EMPLOYEES.DEPARTMENT_ID) AS average_salary 
FROM EMPLOYEES
WHERE EMPLOYEES.DEPARTMENT_ID IS NOT NULL)

SELECT DEPARTMENT_ID, EMPLOYEE_ID, LAST_NAME, SALARY FROM emloyees_avg_dep_sal WHERE emloyees_avg_dep_sal.SALARY > average_salary
ORDER BY DEPARTMENT_ID, SALARY, LAST_NAME

---3
WITH emloyees_min_dep_sal AS
(SELECT EMPLOYEES.DEPARTMENT_ID, EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.LAST_NAME, EMPLOYEES.SALARY, MIN(EMPLOYEES.SALARY) OVER (PARTITION BY EMPLOYEES.DEPARTMENT_ID) AS min_salary 
FROM EMPLOYEES
WHERE EMPLOYEES.DEPARTMENT_ID IS NOT NULL)

SELECT DEPARTMENT_ID, EMPLOYEE_ID, LAST_NAME, SALARY FROM emloyees_min_dep_sal WHERE emloyees_min_dep_sal.SALARY = min_salary 
ORDER BY DEPARTMENT_ID, SALARY, LAST_NAME



WITH europe_managers AS
(
SELECT managers.EMPLOYEE_ID, managers.SALARY FROM
(SELECT DEPARTMENTS.DEPARTMENT_ID FROM
DEPARTMENTS
INNER JOIN (SELECT LOCATIONS.LOCATION_ID FROM LOCATIONS WHERE LOCATIONS.COUNTRY_ID IN (SELECT COUNTRIES.COUNTRY_ID FROM COUNTRIES
WHERE COUNTRIES.REGION_ID IN (SELECT REGIONS.REGION_ID FROM REGIONS WHERE REGIONS.REGION_NAME = 'Europe'))) eu_loc
ON DEPARTMENTS.LOCATION_ID = eu_loc.LOCATION_ID) eu_departments

INNER JOIN
(SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.SALARY, EMPLOYEES.DEPARTMENT_ID FROM
(SELECT UNIQUE EMPLOYEES.MANAGER_ID FROM EMPLOYEES WHERE EMPLOYEES.MANAGER_ID IS NOT NULL) managers_id
INNER JOIN EMPLOYEES
ON managers_id.MANAGER_ID = EMPLOYEES.EMPLOYEE_ID) managers

ON managers.DEPARTMENT_ID = eu_departments.DEPARTMENT_ID)

